In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("student.csv")

In [3]:
df.head()

,age,gender,academic_year,study_hours_per_day,exam_pressure,academic_performance,stress_level,anxiety_score,depression_score,sleep_hours,physical_activity,social_support,screen_time,internet_usage,financial_stress,family_expectation,burnout_score,mental_health_index,risk_level,dropout_risk
0,23,Male,2,5.596071,6.487218,68.411114,4.116950,2.275713,1.986730,6.880545,2.728861,6.470080,4.993801,4.983157,3.446626,3.586147,2.037344,7.074487,Low,1.746601
1,20,Male,3,5.597171,5.631481,67.682159,0.349489,0.000000,0.000000,7.463339,3.690866,0.000000,3.862980,5.136124,2.814039,5.478666,0.000000,9.860204,Low,0.000000
2,29,Male,2,2.580491,6.015297,58.372363,3.476177,2.425201,0.851996,8.946670,3.296720,6.901725,5.428880,3.058333,4.918515,6.068155,0.000000,7.626370,Low,0.696941
3,27,Male,4,4.607208,6.684005,68.925653,6.778843,4.512425,4.285645,4.571380,2.065480,2.349857,6.304842,6.931147,6.915885,6.557540,7.227651,4.649042,High,5.380592
4,24,Male,4,2.186569,4.010945,69.141915,1.854595,1.102558,0.000000,5.989324,4.026504,4.512921,4.903146,5.134903,4.382820,5.934779,0.000000,8.927394,Low,0.000000

In [4]:
df.tail()

,age,gender,academic_year,study_hours_per_day,exam_pressure,academic_performance,stress_level,anxiety_score,depression_score,sleep_hours,physical_activity,social_support,screen_time,internet_usage,financial_stress,family_expectation,burnout_score,mental_health_index,risk_level,dropout_risk
999995,22,Female,3,5.784771,4.922653,79.292283,2.033221,1.238058,0.000000,8.214062,4.404825,9.013047,1.000000,1.664220,5.374860,4.875184,0.000000,8.815294,Low,0.000000
999996,20,Male,1,3.795347,4.706976,70.718819,4.144918,2.768193,1.405596,6.701671,2.664749,8.678769,2.641657,2.923180,5.100452,5.495558,1.166516,7.089896,Low,0.000000
999997,24,Female,3,8.814898,8.750319,79.121184,4.715533,4.138000,1.931592,6.569535,4.219224,4.881412,5.224459,3.855320,2.290888,6.792472,1.997088,6.292909,Low,1.172209
999998,29,Female,4,5.920859,6.678223,69.424255,5.553155,5.681447,1.366879,8.017232,3.634823,5.232852,2.668379,2.951508,5.885972,6.829679,2.731137,5.664240,Low,1.968401
999999,17,Female,2,5.733588,6.061671,58.666123,2.936770,2.533496,0.661940,6.868650,5.501813,2.832691,1.000000,1.000000,5.187394,5.162718,1.342995,7.866661,Low,0.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 20 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   age                   1000000 non-null  int64
 1   gender                1000000 non-null  object
 2   academic_year         1000000 non-null  int64
 3   study_hours_per_day   1000000 non-null  float64
 4   exam_pressure         1000000 non-null  float64
 5   academic_performance  1000000 non-null  float64
 6   stress_level          1000000 non-null  float64
 7   anxiety_score         1000000 non-null  float64
 8   depression_score      1000000 non-null  float64
 9   sleep_hours           1000000 non-null  float64
 10  physical_activity     1000000 non-null  float64
 11  social_support        1000000 non-null  float64
 12  screen_time           1000000 non-null  float64
 13  internet_usage        1000000 non-null  float64
 14  financial_stress      1000000 non-null  float64
 15  family_expectation    1000000 non-null  float64
 16  burnout_score         1000000 non-null  float64
 17  mental_health_index   1000000 non-null  float64
 18  risk_level            1000000 non-null  object
 19  dropout_risk          1000000 non-null  float64
dtypes: float64(16), int64(2), object(2)
memory usage: 152.6+ MB

In [7]:
df.describe()

,age,academic_year,study_hours_per_day,exam_pressure,academic_performance,stress_level,anxiety_score,depression_score,sleep_hours,physical_activity,social_support,screen_time,internet_usage,financial_stress,family_expectation,burnout_score,mental_health_index,dropout_risk
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,22.996456,2.500782,5.001727,5.998810,70.999135,4.246462,2.986413,1.274728,6.501713,3.011153,4.999724,5.018766,5.038116,5.002920,5.983287,1.784073,7.023073,1.324896
std,3.742579,1.117749,1.989340,1.548268,5.660073,1.678998,1.509844,1.221273,1.472972,1.463679,1.976536,1.960599,2.157838,1.976426,1.960972,1.664035,1.310698,1.342727
min,17.000000,1.000000,0.000000,1.000000,42.365714,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.309745,0.000000
25%,20.000000,2.000000,3.650644,4.944647,67.180912,3.102593,1.923747,0.005198,5.491047,1.990596,3.650029,3.651138,3.491114,3.656767,4.647065,0.124810,6.141553,0.000000
50%,23.000000,3.000000,4.998222,5.998906,70.999914,4.244029,2.969514,1.047839,6.501938,3.000619,4.999017,5.003518,5.001542,5.001279,5.999517,1.496505,7.074414,1.009531
75%,26.000000,4.000000,6.345532,7.051914,74.820937,5.385464,4.014996,2.086397,7.514642,4.011208,6.349751,6.351386,6.506834,6.354571,7.351578,2.889473,7.962169,2.173661
max,29.000000,4.000000,14.000000,10.000000,97.246309,10.000000,10.000000,8.530800,10.000000,7.000000,10.000000,12.000000,14.000000,10.000000,10.000000,10.000000,10.000000,9.326226

In [9]:
df = pd.read_excel("excel.xlsx")

In [10]:
df.head()

,Country,Year,Rank,Total,S1: Demographic Pressures,S2: Refugees and IDPs,C3: Group Grievance,E3: Human Flight and Brain Drain,E2: Economic Inequality,E1: Economy,P1: State Legitimacy,P2: Public Services,P3: Human Rights,C1: Security Apparatus,C2: Factionalized Elites,X1: External Intervention
0,Somalia,2023,1st,111.9,10.0,9.0,8.7,8.6,9.1,9.5,9.6,9.8,9.0,9.5,10.0,9.1
1,Yemen,2023,2nd,108.9,9.6,9.6,8.8,6.4,7.9,9.9,9.8,9.6,9.6,8.6,9.9,9.2
2,South Sudan,2023,3rd,108.5,9.7,10.0,8.6,6.5,8.6,8.6,9.8,9.7,8.7,9.9,9.2,9.2
3,Congo Democratic Republic,2023,4th,107.2,9.7,9.8,9.4,6.4,8.4,8.1,9.3,9.3,9.3,8.8,9.6,9.1
4,Syria,2023,5th,107.1,7.4,9.1,9.1,8.0,6.5,9.6,10.0,9.0,9.1,9.4,9.9,10.0

In [11]:
df.tail()

,Country,Year,Rank,Total,S1: Demographic Pressures,S2: Refugees and IDPs,C3: Group Grievance,E3: Human Flight and Brain Drain,E2: Economic Inequality,E1: Economy,P1: State Legitimacy,P2: Public Services,P3: Human Rights,C1: Security Apparatus,C2: Factionalized Elites,X1: External Intervention
174,Switzerland,2023,175th,17.8,2.4,3.2,2.1,1.0,2.4,1.6,0.3,1.6,0.4,1.4,1.0,0.4
175,New Zealand,2023,176th,16.7,1.1,1.2,2.0,1.6,2.6,2.6,0.5,1.1,0.5,1.6,1.4,0.5
176,Finland,2023,177th,16.0,1.7,1.9,0.3,1.5,1.6,2.7,0.4,1.0,0.5,2.0,1.4,1.0
177,Iceland,2023,178th,15.7,1.5,1.5,0.5,1.6,1.5,2.6,0.4,0.9,0.4,0.4,1.8,2.6
178,Norway,2023,179th,14.5,1.4,1.7,3.1,0.7,1.4,1.4,0.4,1.0,0.4,1.4,1.1,0.5

In [12]:
df.describe()

,Year,Total,S1: Demographic Pressures,S2: Refugees and IDPs,C3: Group Grievance,E3: Human Flight and Brain Drain,E2: Economic Inequality,E1: Economy,P1: State Legitimacy,P2: Public Services,P3: Human Rights,C1: Security Apparatus,C2: Factionalized Elites,X1: External Intervention
count,179.0,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000
mean,2023.0,65.832402,5.955866,4.764246,5.574860,5.184358,5.323464,5.687151,5.741341,5.459218,5.436872,5.014525,6.618436,5.072067
std,0.0,23.966251,2.278726,2.373935,2.367757,2.079591,2.068546,2.200741,2.901853,2.581299,2.602588,2.379810,2.427869,2.577801
min,2023.0,14.500000,1.100000,0.500000,0.300000,0.400000,1.400000,1.000000,0.300000,0.900000,0.400000,0.300000,1.000000,0.300000
25%,2023.0,49.000000,4.100000,2.800000,3.600000,3.700000,3.650000,4.100000,3.650000,3.450000,3.600000,3.350000,4.950000,3.150000
50%,2023.0,68.200000,5.900000,4.500000,5.500000,5.600000,5.200000,6.000000,6.400000,5.100000,5.700000,5.100000,7.200000,5.300000
75%,2023.0,82.200000,8.050000,6.450000,7.550000,6.600000,7.200000,7.150000,8.100000,7.950000,7.500000,6.700000,8.550000,7.000000
max,2023.0,111.900000,10.000000,10.000000,9.700000,10.000000,9.600000,9.900000,10.000000,10.000000,9.900000,10.000000,10.000000,10.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179 entries, 0 to 178
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country                           179 non-null    object
 1   Year                              179 non-null    int64
 2   Rank                              179 non-null    object
 3   Total                             179 non-null    float64
 4   S1: Demographic Pressures         179 non-null    float64
 5   S2: Refugees and IDPs             179 non-null    float64
 6   C3: Group Grievance               179 non-null    float64
 7   E3: Human Flight and Brain Drain  179 non-null    float64
 8   E2: Economic Inequality           179 non-null    float64
 9   E1: Economy                       179 non-null    float64
 10  P1: State Legitimacy              179 non-null    float64
 11  P2: Public Services               179 non-null    float64
 12  P3: Human Rights                  179 non-null    float64
 13  C1: Security Apparatus            179 non-null    float64
 14  C2: Factionalized Elites          179 non-null    float64
 15  X1: External Intervention         179 non-null    float64
dtypes: float64(13), int64(1), object(2)
memory usage: 22.5+ KB

In [14]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\erson\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\erson\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel("excel.xlsx")

In [4]:
df.head()

,Country,Year,Rank,Total,S1: Demographic Pressures,S2: Refugees and IDPs,C3: Group Grievance,E3: Human Flight and Brain Drain,E2: Economic Inequality,E1: Economy,P1: State Legitimacy,P2: Public Services,P3: Human Rights,C1: Security Apparatus,C2: Factionalized Elites,X1: External Intervention
0,Somalia,2023,1st,111.9,10.0,9.0,8.7,8.6,9.1,9.5,9.6,9.8,9.0,9.5,10.0,9.1
1,Yemen,2023,2nd,108.9,9.6,9.6,8.8,6.4,7.9,9.9,9.8,9.6,9.6,8.6,9.9,9.2
2,South Sudan,2023,3rd,108.5,9.7,10.0,8.6,6.5,8.6,8.6,9.8,9.7,8.7,9.9,9.2,9.2
3,Congo Democratic Republic,2023,4th,107.2,9.7,9.8,9.4,6.4,8.4,8.1,9.3,9.3,9.3,8.8,9.6,9.1
4,Syria,2023,5th,107.1,7.4,9.1,9.1,8.0,6.5,9.6,10.0,9.0,9.1,9.4,9.9,10.0

In [5]:
df.tail()

,Country,Year,Rank,Total,S1: Demographic Pressures,S2: Refugees and IDPs,C3: Group Grievance,E3: Human Flight and Brain Drain,E2: Economic Inequality,E1: Economy,P1: State Legitimacy,P2: Public Services,P3: Human Rights,C1: Security Apparatus,C2: Factionalized Elites,X1: External Intervention
174,Switzerland,2023,175th,17.8,2.4,3.2,2.1,1.0,2.4,1.6,0.3,1.6,0.4,1.4,1.0,0.4
175,New Zealand,2023,176th,16.7,1.1,1.2,2.0,1.6,2.6,2.6,0.5,1.1,0.5,1.6,1.4,0.5
176,Finland,2023,177th,16.0,1.7,1.9,0.3,1.5,1.6,2.7,0.4,1.0,0.5,2.0,1.4,1.0
177,Iceland,2023,178th,15.7,1.5,1.5,0.5,1.6,1.5,2.6,0.4,0.9,0.4,0.4,1.8,2.6
178,Norway,2023,179th,14.5,1.4,1.7,3.1,0.7,1.4,1.4,0.4,1.0,0.4,1.4,1.1,0.5

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179 entries, 0 to 178
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country                           179 non-null    object
 1   Year                              179 non-null    int64
 2   Rank                              179 non-null    object
 3   Total                             179 non-null    float64
 4   S1: Demographic Pressures         179 non-null    float64
 5   S2: Refugees and IDPs             179 non-null    float64
 6   C3: Group Grievance               179 non-null    float64
 7   E3: Human Flight and Brain Drain  179 non-null    float64
 8   E2: Economic Inequality           179 non-null    float64
 9   E1: Economy                       179 non-null    float64
 10  P1: State Legitimacy              179 non-null    float64
 11  P2: Public Services               179 non-null    float64
 12  P3: Human Rights                  179 non-null    float64
 13  C1: Security Apparatus            179 non-null    float64
 14  C2: Factionalized Elites          179 non-null    float64
 15  X1: External Intervention         179 non-null    float64
dtypes: float64(13), int64(1), object(2)
memory usage: 22.5+ KB

In [7]:
df.describe()

,Year,Total,S1: Demographic Pressures,S2: Refugees and IDPs,C3: Group Grievance,E3: Human Flight and Brain Drain,E2: Economic Inequality,E1: Economy,P1: State Legitimacy,P2: Public Services,P3: Human Rights,C1: Security Apparatus,C2: Factionalized Elites,X1: External Intervention
count,179.0,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000
mean,2023.0,65.832402,5.955866,4.764246,5.574860,5.184358,5.323464,5.687151,5.741341,5.459218,5.436872,5.014525,6.618436,5.072067
std,0.0,23.966251,2.278726,2.373935,2.367757,2.079591,2.068546,2.200741,2.901853,2.581299,2.602588,2.379810,2.427869,2.577801
min,2023.0,14.500000,1.100000,0.500000,0.300000,0.400000,1.400000,1.000000,0.300000,0.900000,0.400000,0.300000,1.000000,0.300000
25%,2023.0,49.000000,4.100000,2.800000,3.600000,3.700000,3.650000,4.100000,3.650000,3.450000,3.600000,3.350000,4.950000,3.150000
50%,2023.0,68.200000,5.900000,4.500000,5.500000,5.600000,5.200000,6.000000,6.400000,5.100000,5.700000,5.100000,7.200000,5.300000
75%,2023.0,82.200000,8.050000,6.450000,7.550000,6.600000,7.200000,7.150000,8.100000,7.950000,7.500000,6.700000,8.550000,7.000000
max,2023.0,111.900000,10.000000,10.000000,9.700000,10.000000,9.600000,9.900000,10.000000,10.000000,9.900000,10.000000,10.000000,10.000000